require "test/unit"

require_relative "vector_test"
require_relative "box_test"
require_relative "shape_test"
require_relative "lambda_test"
require_relative "picture_test"
require_relative "mirror_test"
require_relative "style_test"
require_relative "fitting_test"
